"""Create Voting Table

Revision ID: 22cc0297cd7a
Revises: 
Create Date: 2016-04-15 14:42:03.141872

"""

# revision identifiers, used by Alembic.
revision = '22cc0297cd7a'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_doobie_vote',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('doobie_id', sa.BigInteger(), nullable=True),
    sa.Column('vote', sa.Integer(), nullable=True),
    sa.Column('create_ts', sa.DateTime(), nullable=True),
    sa.Column('update_ts', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doobie_id'], [u'db_doobie_mapping.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'db_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_doobie_vote_doobie_id'), 'db_doobie_vote', ['doobie_id'], unique=False)
    op.create_index(op.f('ix_db_doobie_vote_id'), 'db_doobie_vote', ['id'], unique=True)
    op.create_index(op.f('ix_db_doobie_vote_user_id'), 'db_doobie_vote', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_doobie_vote_user_id'), table_name='db_doobie_vote')
    op.drop_index(op.f('ix_db_doobie_vote_id'), table_name='db_doobie_vote')
    op.drop_index(op.f('ix_db_doobie_vote_doobie_id'), table_name='db_doobie_vote')
    op.drop_table('db_doobie_vote')
    ### end Alembic commands ###
